<a href="https://colab.research.google.com/github/Tsadza323/assignment-4-for-week-4/blob/main/week_5_supervised_machine_learning_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
df= pd.read_csv("/content/Reference_geotherm2Dmodel_base (1).csv")
df.head()

        pres       temp   x    z   log10PER
0  9635610.0  82.126015  10 -990 -14.190209
1  9635685.0  82.074013  30 -990 -14.193206
2  9635831.0  81.971626  50 -990 -14.193851
3  9636048.0  81.821793  70 -990 -14.195125
4  9636333.0  81.628616  90 -990 -14.200741

In [13]:
df.head()
#display the first five rows of the dataset#

        pres       temp   x    z   log10PER
0  9635610.0  82.126015  10 -990 -14.190209
1  9635685.0  82.074013  30 -990 -14.193206
2  9635831.0  81.971626  50 -990 -14.193851
3  9636048.0  81.821793  70 -990 -14.195125
4  9636333.0  81.628616  90 -990 -14.200741

In [14]:
df.info()
#Check the column names and data types#

print(df.shape)
#Check the number of rows and columns#

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pres      2500 non-null   float64
 1   temp      2500 non-null   float64
 2   x         2500 non-null   int64
 3   z         2500 non-null   int64
 4   log10PER  2500 non-null   float64
dtypes: float64(3), int64(2)
memory usage: 97.8 KB
(2500, 5)

In [15]:
print(df.isnull().sum())
#Check for missing values in each column#

pres        0
temp        0
x           0
z           0
log10PER    0
dtype: int64

In [16]:
#Understand the input features#
X=df[["x","z","log10PER"]]

#select the target output#
y=df["temp"]

#Display the input features#
print(X.head())

#Display the target output#
print(y.head())

    x    z   log10PER
0  10 -990 -14.190209
1  30 -990 -14.193206
2  50 -990 -14.193851
3  70 -990 -14.195125
4  90 -990 -14.200741
0    82.126015
1    82.074013
2    81.971626
3    81.821793
4    81.628616
Name: temp, dtype: float64

In [20]:
#Split the dataset into 80% training and 20% testing#
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#Display the sizes of the datasets#
print("Training features:",X_train.shape)
print("Testing features:",X_test.shape)
print("Testing target:",y_test.shape)
print("Training target:",y_train.shape)

Training features: (2000, 3)
Testing features: (500, 3)
Testing target: (500,)
Training target: (2000,)

In [21]:
from sklearn.linear_model import LinearRegression

#Create the linear regression model#
linear_model=LinearRegression()

#train model#
linear_model.fit(X_train,y_train)

print("linear Regression model trained succesfully.")

linear Regression model trained succesfully.

In [22]:
from sklearn.ensemble import RandomForestRegressor
#create the random Forest model#
forest_model=RandomForestRegressor(n_estimators=100,random_state=42)

#train the model#
forest_model.fit(X_train,y_train)

print("Random Forest model trained succesfully.")

Random Forest model trained succesfully.

In [24]:
#Predict temeperatures using linear Regression#
linear_predictions=linear_model.predict(X_test)

#Predict temeperatures using Random Forest#
forest_predictions=forest_model.predict(X_test)

#Display the first five predictions#
print("Actual temperatures:")
print(y_test.head().to_numpy())
print("Linear Regression predictions:")
print(linear_predictions[:5])
print("Random Forest predictions:")
print(forest_predictions[:5])

Actual temperatures:
[33.20398712 37.47706223 38.97513962 20.81379318 22.3489666 ]
Linear Regression predictions:
[29.79314569 42.54184732 43.6993576  14.09677831 32.35238108]
Random Forest predictions:
[33.04872315 37.55390591 38.57208732 20.80465054 22.21119598]

In [25]:
from sklearn.metrics import (mean_absolute_error,mean_squared_error,r2_score)
import numpy as np

#Evaluate the linear regression model#
linear_mae=mean_absolute_error(y_test,linear_predictions)
linear_mse=mean_squared_error(y_test,linear_predictions)
linear_rmse=np.sqrt(linear_mse)
linear_r2=r2_score(y_test,linear_predictions)

#Evaluate the Random Forest model#
forest_mae=mean_absolute_error(y_test,forest_predictions)
forest_mse=mean_squared_error(y_test,forest_predictions)
forest_rmse=np.sqrt(forest_mse)
forest_r2=r2_score(y_test,forest_predictions)

print("Linear Regression Metrics:")
print("MAE:",linear_mae)
print("MSE:",linear_mse)
print("RMSE:",linear_rmse)
print("R2 Score:",linear_r2)

print("\nRandom Forest Metrics:")
print("MAE:",forest_mae)
print("MSE:",forest_mse)
print("RMSE:",forest_rmse)
print("R2 Score:",forest_r2)

Linear Regression Metrics:
MAE: 4.4439597711579895
MSE: 30.065244887730827
RMSE: 5.483178356366937
R2 Score: 0.9024145995396757

Random Forest Metrics:
MAE: 0.18572044299959872
MSE: 0.08043773320178536
RMSE: 0.2836154671413133
R2 Score: 0.9997389161992217

In [26]:
import pandas as pd
#Create a table comparing both models#
results=pd.DataFrame({
    "Model":["Linear Regression","Random Forest"],
    "MAE":[linear_mae,forest_mae],
    "MSE":[linear_mse,forest_mse],
    "RMSE":[linear_rmse,forest_rmse],
    "R2 Score":[linear_r2,forest_r2]
})
print(results)

               Model      MAE        MSE      RMSE  R2 Score
0  Linear Regression  4.44396  30.065245  5.483178  0.902415
1      Random Forest  0.18572   0.080438  0.283615  0.999739

In [ ]:
DISCUSSION OF RESULTS
The results shows that random forest Regression performed better than linear regression in predicting reservoir temeperature.Random Forest archieved a lower MAE of 0.1857, MSE 0f 0.080438 and RMSE of 0.283615 compared to linear regression, which had an MAE of 4.44396, MSE of 30.065245 and RMSE of 5.483178.Random forest also archieved a higher R^2 score pf 0.999739 compared to 0.902415 for linear regression. This indicates that Random forest made more accurate predictions and explained a greater proportion of the variation of temperature. Therefore, Random forest was the better-performing model for this dataset